# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicpro', '0002_simple'),
        ('basicpro', '0003_simple'),
    ]

    operations = [
    ]
