# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicpro', '0003_simple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=255)),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicpro.Simple')),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicpro.Sample')),
            ],
        ),
    ]
